version: '3'
services: 
  frontend:
    restart: always
    build: ./frontend
    ports: 
      - 9168:8954
  api:
    restart: always
    build: ./api
    ports:
      - 5555:5000
  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    restart: always
    image: adminer
    ports:
      - 3218:8080
      
volumes:
  mysql_data:

